---
  - name: Install Node Exporter
    get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp

  - name: Make Prometheus Directory
    file:
      path: "/etc/prometheus"
      state: directory

  - name: UnArchive Gzip
    shell: tar xfz /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz -C /etc/prometheus/

  - name: Remove Gzip File
    file:
      path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      state: absent

  - name: Make Textfile Directory
    file:
      path: "{{ prometheus_textfile_directory }}"
      state: directory

  - name: Configure Systemd
    template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service

  - name: Systemd Daemon Reload
    systemd:
      daemon_reload: yes

  - name: Systemd Enabled Node Exporter
    systemd:
      name: node_exporter.service
      enabled: yes

  - name: Systemd Start Node Exporter
    systemd:
      name: node_exporter.service
      state: started