---
  - name: Download OtelCollector
    get_url:
        url: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v{{ otel_version }}/otelcol-contrib_{{ otel_version }}_linux_amd64.rpm
        dest: /tmp

  - name: Install OtelCollector
    shell: rpm -Uvh /tmp/otelcol-contrib_{{ otel_version }}_linux_amd64.rpm

  - name: Remove RPM File
    file:
      path: /tmp/otelcol-contrib_{{ otel_version }}_linux_amd64.rpm
      state: absent

  - name: Configure OtelCollector
    template:
      src: config.yaml.j2
      dest: /etc/otelcol-contrib/config.yaml

  - name: Restart OtelCollector
    systemd:
      name: otelcol-contrib.service
      state: restarted