---
  - name: Download MongoDB exporter
    get_url:
      url: "https://github.com/percona/mongodb_exporter/releases/download/v{{ mongodb_exporter_version }}/mongodb_exporter-{{ mongodb_exporter_version }}.linux-amd64.tar.gz"
      dest: /tmp

  - name: Extract MongoDB exporter
    shell: tar xfz /tmp/mongodb_exporter-{{ mongodb_exporter_version }}.linux-amd64.tar.gz -C /etc/prometheus/

  - name: Remove Gzip File
    file:
      path: "/tmp/mongodb_exporter-{{ mongodb_exporter_version }}.linux-amd64.tar.gz"
      state: absent

  - name: Install MongoDB exporter systemd unit file
    template:
      src: mongodb_exporter.service.j2
      dest: /etc/systemd/system/mongodb_exporter.service

  - name: Systemd Daemon Reload
    systemd:
      daemon_reload: yes

  - name: Systemd Enabled MongoDB exporter service
    systemd:
      name: mongodb_exporter
      enabled: yes

  - name: Systemd Start MongoDB exporter service
    systemd:
      name: mongodb_exporter
      state: started